### ISSUE TITLE
Web-Tool

### ISSUE THREAD

**Issue by sqxssss** [Reverier-Xu/ICTFE#6]
试试把postman或者hackbar之类的集成一下么qwq

俺可以来做

**Comment by Reverier-Xu** [comment]
WebPanel 任大佬发挥啦~ 写完了之后pull过来就可以了, 万分感谢~
在数据流的节点编辑器分区中, 我用节点简单的实现了一下get和post, 不过这种方法多少有点蛋疼, 还是需要一个集成度好点的工具.
目前ICTFE中集成的简单浏览器只支持最基础的访问, F12等开发者功能都不具备, 如果能集成到浏览器那个panel里面更好, 不过我感觉不是很好实现,, 所以看情况8
